### ISSUE TITLE
Allow conversion to builder with the From trait

### ISSUE THREAD

**Issue by nicflower** [elastio/bon#69]
When applying the builder pattern I find that something useful is the conversion from the built type to the builder, for example:

```rust
#[derive(Default)]
struct Animal {
    name: String,
    color: String,
    size: String,
}

struct AnimalBuilder {
    animal: Animal
}

impl From<Animal> for AnimalBuilder {
    fn from(animal: Animal) -> Self {
        Self {
            animal,
        }
    }
}
````

this is useful when I want to edit just 1 or two fields of the objects and leave the others, because it would allow something like this:
````rust
let horse = Animal::builder().name("Jon").color("black").size("small").build();
// horse does stuff and turns into something else
let new_horse = horse.into().size("very big").color("brown").build();
````
is there any way to achieve this behaviour? If not would you be interested in having something like this?

### A note for the community from the maintainers

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the maintainers with prioritizing it. You may add a comment describing your real use case related to this issue for us to better understand the problem domain.

**Comment by Veetaha** [comment]
Hi, thank you for creating the issue! I see the use case here. What you could do today with `bon` to reuse a "common set of data" is using the variation of the ["Shared Partial Builder"](https://elastio.github.io/bon/guide/patterns/conditional-building#shared-partial-builder) pattern with a closure wrapper. 

**Example:**

```rust
let builder = || Animal::builder().name("Jon").build();

let horse_1 = builder().color("black").size("small").build();
let horse_2 = builder().color("white").size("medium").build();
```

---

The idea suggested by your of having a `From<T> for TBuilder` has a flaw in that `TBuilder` generated by `bon` specifically restricts the usage of setters to only be called once per member to prevent unintentional overwrites. For example, today this doesn't compile:

```rust
#[bon::builder]
struct Example {
    field: u32
}

let complete_builder = Example::builder().field(42);

// This fails to compile because the field `field` was already set:
complete_builder.field(55);

// Now imagine we have the `From<Example>` to `ExampleBuilder`
// We also need some what to denote a "complete" builder type state
// Right now that's not possible, since the builder's generics type signature
// is not stable and documented in `bon`. But let's suppose it's already stable
// for the purpose of this example.
let complete_builder: ExampleBuilder<CompleteState> = Example { field: 42 }.into();

// We can't call the setter for `field` because it was already set (from the `Example` struct in From<>` impl)
complete_buillder.field(55);
```

The builder would need to have `update_{member}(&mut self)` methods to explicitly update the existing data in the builder without changing the builder's type state. Which is something that I'm planning to add to `bon`: an ability to mutate the fields that were set in the builder.

---

Instead, what I think you'd like to have is the ability to generate setter methods for your struct that use builder-like syntax. I think generating setters is something that can be implemented in `bon` as a separate proc macro (maybe a derive macro specifically).

There are existing crates that generate setters, for example [getset](https://docs.rs/getset/latest/getset/) (although this one looks unmaintained, it wasn't updated in the last 3 years). 

The idea of generating setters was discussed here as well: https://github.com/elastio/bon/issues/24#issuecomment-2259336170. It will be cool if `bon` could do that, because it would yield the setters API that would be consistent with its builder API conventions. One day `bon` will get there, but my current priority for `bon` is to get the `#[builder]` macro feature-complete.

**Comment by nicflower** [comment]
If I go ahead with the setters pattern you mentioned, would you consider a PR, or is it something you'd prefer to handle later?

**Comment by Veetaha** [comment]
I'm closing this issue in favour of https://github.com/elastio/bon/issues/147
