### ISSUE TITLE
into triggers `clippy::impl_trait_in_params`

### ISSUE THREAD

**Issue by EdJoPaTo** [elastio/bon#78]
See https://rust-lang.github.io/rust-clippy/master/index.html#/impl_trait_in_params.

Reproduce:

```rust
#![warn(clippy::impl_trait_in_params)]

fn main() {
    let example = Example::builder().content(42).build();
    dbg!(example.content);
}

#[bon::builder]
pub struct Example {
    #[builder(into)]
    content: i32,
}
```

Maybe it's a good idea to follow this lints suggestion and move to `fn content<T: Into<i32>(self, value: T)`. Otherwise, maybe ignore this lint by default (like other non clippy lints are already ignored)

**Comment by Veetaha** [comment]
Yeah, this lint doesn't make sense for the particular case of setters that accept a single parameter with `impl Into` trait.

If you want to make PR, the place to add this attribute is on the setter generation code here: https://github.com/elastio/bon/blob/d49a3b56790768daafb4b0e869f0b5e2dd722d29/bon-macros/src/builder/builder_gen/setter_methods.rs#L272-L284

**Comment by EdJoPaTo** [comment]
Not sure whether it really doesn't make sense. Having `content::<u8>("42".parse())` could be neat for people to use?

**Comment by Veetaha** [comment]
I see, didn't think of this `parse()` case, however, I still believe that using `impl Trait` syntax is better, just because it's easier to read it this way. The type of the value is visible right in the parameter's type annotation and you don't have to move your eyes to the generic parameter declaration. Also, the generic parameter will have an ugly name with `__`  prefix to prevent potential collisions with other generic parameters in scope from user's structs/functions.

Compare reading this:

```rust
fn member(value: impl Into<String>) -> NextBuilderState
```
to this:
```rust
fn member<__T: Into<String>>(value: __T) -> NextBuilderState
```

**Comment by Veetaha** [comment]
Notice that the generated code doesn't even qualify the `Into` trait with `::core::convert::Into` in the sake of better readability.

**Comment by Veetaha** [comment]
Prefix `__` will be required in such a case because shadowing must not happen (it's actually a compile error if you try to shadow a generic parameter). Suppose there is a struct like this:

```rust
#[bon::builder]
struct MyLovelyStruct<T> {
    #[builder(into)]
    items: Vec<T>
}
```
The setter that will be generated is this:

```rust
impl<T, __State: /* some bounds */> MyLovelyStructBuilder<T, __State> {
    fn items(value: impl Into<Vec<T>>) -> MyLovelyStructBuilder<T, /* new state */> { /**/ }
}
```
Now if the setter defines a generic parameter that shadows `T`, things break. This won't work:
```rust
fn items<T: Into<Vec<T>>(/**/);
```
Error:
```log
  |
5 | impl<T> MyLovelyStruct<T> {
  |      - first use of `T`
6 |     fn items<T: Into<Vec<T>>>(&mut self, value: T) {
  |              ^ already used
```

---

As for me people far more often read the code and type signatures, than have use cases for passing a generic parameter to the function that accepts an `impl Into`. If the setter accepts an `impl Into` and you need to provide a type hint for it, then it's already a case of bad design (maybe `Into` shouldn't have been enabled in the first place), which must be quite rare. I think requiring the user to move the expression into a variable with an explicit type in such case is fine, than compromising the readiability

**Comment by Veetaha** [comment]
Another example, of a widely used library that uses builders is AWS SDK. It uses `impl Into<String>` syntax for string members:
https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/operation/put_object/builders/struct.PutObjectInputBuilder.html#method.bucket

**Comment by EdJoPaTo** [comment]
> If […] you need to provide a type hint for it, then it's already a case of bad design (maybe `Into` shouldn't have been enabled in the first place)

I think that's a good argument. I like the discussion!

So the remaining action from this is to add an `#[allow` to this macro, so users of the lint can still use bon. I'd like to attempt a PR for that (hopefully in a few hours).
