### ISSUE TITLE
Set an msrv requirement and test it on CI

### ISSUE THREAD

**Issue by Veetaha** [elastio/bon#81]
The current code is tested with `1.80.1` on CI, but I tried to keep it compatible with older versions manually. 
We need to set the `required-rust-version` in Cargo.toml and the MSRV version to the tests on CI. CI should have matrix jobs for each check that validate the code on both MSRV and latest stable

**Comment by EdJoPaTo** [comment]
Personally I would try to get 1.63 (or earlier) as MSRV in order to support current Debian bullseye. That would allow for tools depending on bon to be packages natively for Debian Bullseye.

Also, `-Zmsrv-policy` (part of the upcoming `resolver = "3"` / edition 2024) should help with that. See https://github.com/rust-lang/cargo/issues/13873

The following graphic contains the Rust version in currently supported (no out of support) distros known to repology.org:

[![Packaging status](https://repology.org/badge/vertical-allrepos/rust.svg?columns=2&exclude_unsupported=1)](https://repology.org/project/rust/versions)

**Comment by Veetaha** [comment]
Thank you for the insight! [`derive-builder`](https://github.com/colin-kiegel/rust-derive-builder) supports `1.56`, although it depends on `syn 2.0` that supports `1.61+`. I believe it's better to follow `syn` in this regard, since any change to `syn` may accidentally break its current untested compatibility with `rustc 1.56`.

**Comment by Veetaha** [comment]
Correction `syn 2.0.56` supports rust version `1.56`, but `syn 2.0.57` bumped that requirement. I think to be able to replace `derive-builder` we need to do the same then. Not sure how hard it'll be and if it will be hard I'm fine to use `1.61` as MSRV to follow the cutting edge of `syn`.

**Comment by Veetaha** [comment]
> Personally I think it's fine to bump MSRV when the `rust-version` on the published versions on crates.io is correct

What do you mean by "when the `rust-version` is correct"? If it's incorrect, then it's a bujg

**Comment by Veetaha** [comment]
I've set MSRV to 1.70.0 for now. The problem with making it lower is that crates we use for testing (such as trybuild, for example), don't compile on versions lower than that. I may consider lowering this requirement in the future if a compelling use case emerges.

**Comment by Veetaha** [comment]
I created a followup issue to keep lowering the MSRV (#102). This first iteration is just a good enough first attempt at lowering it.

**Comment by Veetaha** [comment]
This feature is now available in `bon` 2.2. Here is the [release blog post on Reddit](https://www.reddit.com/r/rust/comments/1fc0ai7/media_nextgen_builder_macro_bon_22_release_derive/)
